export enum EHTTPAction {
    GET_LIST = 'GET_LIST',
    GET_ITEM = 'GET_ITEM',
    CREATE_ITEM = 'CREATE_ITEM',
    UPDATE_ITEM = 'UPDATE_ITEM',
    DELETE_ITEM = 'DELETE_ITEM',
    CREATE_ITEMS = 'CREATE_ITEMS',
    UPDATE_ITEMS = 'UPDATE_ITEMS',
    DELETE_ITEMS = 'DELETE_ITEMS',
}